# Generated by Django 3.2.6 on 2021-09-09 17:01

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.TextField()),
                ('account_number', models.CharField(max_length=20)),
                ('bank_name', models.TextField()),
                ('bank_address', models.TextField()),
                ('swift_code', models.CharField(max_length=20)),
                ('iban_code', models.CharField(max_length=20)),
                ('other_details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(blank=True, max_length=20, null=True)),
                ('order_date', models.DateField(blank=True, null=True)),
                ('order_time', models.TimeField(blank=True, null=True)),
                ('customer_uid', models.CharField(blank=True, max_length=20, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=20, null=True)),
                ('customer_email', models.CharField(blank=True, max_length=20, null=True)),
                ('billing_name', models.CharField(blank=True, max_length=20, null=True)),
                ('billing_address', models.TextField(blank=True, null=True)),
                ('billing_district', models.CharField(blank=True, max_length=20, null=True)),
                ('billing_state', models.CharField(blank=True, max_length=20, null=True)),
                ('billing_zip_code', models.CharField(blank=True, max_length=20, null=True)),
                ('billing_country', models.CharField(blank=True, max_length=20, null=True)),
                ('billing_phone_No', models.CharField(blank=True, max_length=20, null=True)),
                ('shipping_name', models.CharField(blank=True, max_length=20, null=True)),
                ('shipping_address', models.CharField(blank=True, max_length=20, null=True)),
                ('shipping_district', models.CharField(blank=True, max_length=20, null=True)),
                ('shipping_state', models.CharField(blank=True, max_length=20, null=True)),
                ('shipping_zip_code', models.CharField(blank=True, max_length=20, null=True)),
                ('shipping_country', models.CharField(blank=True, max_length=20, null=True)),
                ('shipping_phone_No', models.CharField(blank=True, max_length=20, null=True)),
                ('order_currency', models.CharField(blank=True, max_length=20, null=True)),
                ('order_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_taxes', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('order_discounts', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('order_subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_shipping_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('order_ship_TBD', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('order_cart_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_cart_taxes', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('order_cart_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('order_grand_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_coupon_code', models.CharField(blank=True, max_length=20, null=True)),
                ('order_coupon_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('order_status', models.CharField(blank=True, max_length=20, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=20, null=True)),
                ('payment_live', models.BooleanField()),
                ('payment_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_response', models.TextField(blank=True, null=True)),
                ('payment_successful', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_uid', models.CharField(max_length=20)),
                ('item_quantity', models.PositiveIntegerField()),
                ('item_product_id', models.CharField(max_length=20)),
                ('item_product_type', models.CharField(max_length=20)),
                ('item_product_title', models.CharField(max_length=20)),
                ('item_return_days', models.IntegerField()),
                ('item_exchange_days', models.IntegerField()),
                ('item_product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item_basic_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item_discount_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item_tax_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item_sub_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('seller_cleared', models.BinaryField(default=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='orderDataApp.order')),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_uid', models.CharField(max_length=20)),
                ('seller_unique_code', models.CharField(max_length=20)),
                ('seller_name', models.CharField(max_length=20)),
                ('seller_company', models.CharField(max_length=20)),
                ('seller_email', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SellerDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('uncleared_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('Seller', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='orderDataApp.seller')),
                ('bank_account', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='orderDataApp.bankaccount')),
            ],
        ),
        migrations.CreateModel(
            name='SellerNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('date_time', models.DateTimeField(default=datetime.datetime.now)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('seller_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orderDataApp.sellerdetail')),
            ],
        ),
        migrations.CreateModel(
            name='OrderNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField()),
                ('date_time', models.DateTimeField(default=datetime.datetime.now)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orderDataApp.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItemNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField()),
                ('date_time', models.DateTimeField(default=datetime.datetime.now)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orderDataApp.orderitem')),
            ],
        ),
        migrations.AddField(
            model_name='orderitem',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orderDataApp.seller'),
        ),
    ]
