# Generated by Django 3.2.6 on 2021-09-10 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderDataApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='seller_cleared',
            field=models.BooleanField(default=False),
        ),
    ]
