# Generated by Django 3.2.6 on 2021-09-10 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderDataApp', '0002_alter_orderitem_seller_cleared'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
